import type { Metadata } from "next";
import "@/lib/fontawesome";
import "./globals.css";
import Headeravbar from "@/components/Navbar/Headeravbar";
import { Kanit } from "next/font/google";

const kanit = Kanit({
  subsets: ["latin", "thai"],     // หรือ ["latin", "thai"] ถ้าใช้ภาษาอังกฤษด้วย
  weight: ["200", "400", "700"], 
  
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="th" className={kanit.className}>
      <body>
        <Headeravbar />
        {children}
      </body>
    </html>
    
  );

}
 